[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables must be set in Netlify UI:
# Site settings > Environment variables
# Required: STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET, MONGODB_URI, MONGODB_DB

